@Catalog.Api_HostAddress = https://localhost:5050

GET {{Catalog.Api_HostAddress}}/products
Accept: application/json

###

POST {{Catalog.Api_HostAddress}}/products
Accept: application/json
Content-Type: application/json

{
    "Name": "New Product A",
    "Category": ["c1", "c2"],
    "Description": "Description Product A",
    "ImageFile": "ImageFile Product A",
    "Price": 199
}