@Catalog.Api_HostAddress = https://localhost:6060


###

POST {{Catalog.Api_HostAddress}}/products
Accept: application/json
Content-Type: application/json
{
    "Name": "New Product A",
    "Category": ["c1", "c2"],
    "Description": "Description Product A",
    "ImageFile": "ImageFile Product A",
    "Price": 99
}

###

GET {{Catalog.Api_HostAddress}}/products
Accept: application/json

###

GET {{Catalog.Api_HostAddress}}/products/5334c996-8457-4cf0-815c-ed2b77c4ff62
Accept: application/json

###
PUT {{Catalog.Api_HostAddress}}/products
Accept: application/json
Content-Type: application/json
{
    "id": "019416b2-ba1a-4f78-92a5-6d753bd0f574",
    "Name": "Sample Prod",
    "Category": ["c1", "c2","c3"],
    "Description": "Sample Prod Description",
    "ImageFile": "Sample Prod ImageFile",
    "Price": 105
}

###
DELETE {{Catalog.Api_HostAddress}}/products/5334c996-8457-4cf0-815c-ed2b77c4ff6
Accept: application/json